name: Build and deploy
on:
  push:
    branches: [ "gd" ]
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t zou8944/web3-blog .
      - name: Publish to docker hub
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          docker push zou8944/web3-blog:latest
          docker logout
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Deploy
        run: |
          ssh-keyscan -H ec2-35-153-93-31.compute-1.amazonaws.com >> ~/.ssh/known_hosts
          ssh ubuntu@ec2-35-153-93-31.compute-1.amazonaws.com \
            "sudo docker pull zou8944/web3-blog:latest && \
             sudo docker stop web3-blog && \
             sudo docker rm web3-blog && \
             sudo docker run -d --name web3-blog -v /home/ubuntu/.web3-blog/config:/config -p 9000:9000 -e ENV=prod zou8944/web3-blog:latest "
          echo "server deploy done"