name: Create and upload docker image
on:
  push:
    branches: [ "gd" ]
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t zou8944/web3-blog .
      - name: Publish to docker hub
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          docker push zou8944/web3-blog:latest
          docker logout